# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('body', models.TextField()),
                ('publish_date', models.DateTimeField(verbose_name='published date')),
                ('gPlus', models.IntegerField()),
            ],
        ),
    ]
